# Generated by Django 2.1.2 on 2018-10-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_email', models.CharField(max_length=30)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_subject', models.CharField(max_length=30)),
                ('contact_message', models.CharField(max_length=30)),
            ],
        ),
    ]
