# Generated by Django 2.1.2 on 2018-11-03 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppoinmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoinment_name', models.CharField(max_length=30, verbose_name='Nome do paciente')),
                ('appoinment_email', models.CharField(max_length=30, verbose_name='Email')),
                ('appoinment_date', models.CharField(max_length=50, verbose_name='Data da consulta')),
                ('appoinment_phone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('appoinment_message', models.CharField(max_length=30, verbose_name='Mensagem')),
                ('appoinment_sent_date', models.DateTimeField(default=django.utils.timezone.now, max_length=35, verbose_name='Mensagem enviada em')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_email', models.CharField(max_length=30)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_subject', models.CharField(max_length=30)),
                ('contact_message', models.CharField(max_length=30)),
                ('contact_sent_date', models.DateTimeField(default=django.utils.timezone.now, max_length=35)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
