# Generated by Django 2.1.2 on 2018-11-11 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120, unique=True)),
                ('patient_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_updated_date', models.DateTimeField(auto_now=True)),
                ('patient_email', models.EmailField(max_length=120, unique=True)),
                ('patient_source', models.CharField(choices=[('indicacao_paciente', 'Indicação paciente'), ('mídia', 'Mídia'), ('indicacao_medica', 'Indicação médica'), ('indicacao_odonto', 'Indicação odontológica')], default='indicação', max_length=120)),
                ('patient_phone', models.CharField(max_length=120)),
                ('patient_phone_backup', models.CharField(max_length=120)),
                ('patient_addreess', models.CharField(max_length=120)),
                ('patient_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
