# Generated by Django 2.1.2 on 2018-11-12 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='patient_addreess',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='patient_address',
            field=models.CharField(max_length=120, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_active',
            field=models.BooleanField(default=True, verbose_name='Status do Paciente'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Incrição'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_email',
            field=models.EmailField(max_length=120, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_phone',
            field=models.CharField(max_length=120, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_phone_backup',
            field=models.CharField(max_length=120, verbose_name='Telefone 2'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='patient_source',
            field=models.CharField(choices=[('indicacao_paciente', 'Indicação paciente'), ('mídia', 'Mídia'), ('indicacao_medica', 'Indicação médica'), ('indicacao_odonto', 'Indicação odontológica')], default='indicação', max_length=120, verbose_name='Indicação'),
        ),
    ]
